github.com:
    users:
        Guneshwar24:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: Guneshwar24
